FROM node:10-alpine

ARG BTC_EXPLORER_BTC_NODE
ARG BTC_EXPLORER_TABLE_BLOCKS
ARG BTC_EXPLORER_TABLE_TXS
ARG BTC_EXPLORER_DB_NAME
ARG BTC_EXPLORER_RETHINK

COPY . /proj/

WORKDIR /proj

RUN yarn

ENTRYPOINT [ "yarn", "start" ]